[theme]
primaryColor="#2878b9"
backgroundColor="#dae5ef"
secondaryBackgroundColor="#586e75"
textColor="#44546a"
<link href="http://fonts.cdnfonts.com/css/tenorite" rel="stylesheet">
font-family: 'Tenorite', sans-serif;                             
